backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/assets/blog" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/blog"
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}